# Generated by Django 2.0.5 on 2018-05-26 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('changed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('changed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('caption', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='authors', to='yallib.Author')),
                ('genres', models.ManyToManyField(related_name='genres', to='yallib.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('changed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
