# Generated by Django 2.0.5 on 2018-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yallib', '0002_auto_20180611_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', 'BLOCKED'), ('1', 'ACTIVE'), ('2', 'DELETED'), ('3', 'SUSPENDED')], default=1, max_length=50),
        ),
    ]
